# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleFav' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleFav
   pod 'Parse'
   pod 'AlamofireImage'

  target 'SimpleFavTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'Parse'
     pod 'AlamofireImage'
  end

  target 'SimpleFavUITests' do
    # Pods for testing
     pod 'Parse'
     pod 'AlamofireImage'
  end

end
